// SIGN UP
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

// SIGN IN
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";

// SIGN OUT
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";

// COMMON
export const SET_LOADING = "SET_LOADING";
export const SET_ALERT = "SET_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

// PRODUCTS
export const SET_PRODUCTS_SUCCESS = "SET_PRODUCTS_SUCCESS";
export const SET_PRODUCTS_ERROR = "SET_PRODUCTS_ERROR";

// PRODUCT
export const SET_PRODUCT_SUCCESS = "SET_PRODUCT_SUCCESS";
export const SET_PRODUCT_ERROR = "SET_PRODUCT_ERROR";

// ADD PRODUCT
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";
export const ADD_PRODUCT_PRODUCTS_ERROR = "ADD_PRODUCT_PRODUCTS_ERROR";

// EDIT PRODUCT
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR";